apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-pod
spec:
  selector:
    app: my-pod
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
