apiVersion: v1   # API version for Pod resource
kind: Pod        # Declares this manifest as a Pod
metadata: 
  name: my-pod   # Name of the Pod

spec:
  containers:
    - name: nginx   # Container name inside the Pod
      image: nginx:latest   # Container image to run (latest Nginx)
      ports:
        - containerPort: 80   # Exposes port 80 (default HTTP port) inside the container

      volumeMounts:   # Defines where to mount volumes inside the container
        - mountPath: "/usr/share/nginx/html"   # Path inside container where volume will be mounted
          name: my-vol   # Must match the volume name defined below

  volumes:   # Volumes available to the Pod
    - name: my-vol   # Name of the volume (referenced above in volumeMounts)
      persistentVolumeClaim:
        claimName: my-pvc   # PVC name → binds this volume to the PVC "my-pvc"
 