apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: mysql:latest
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
           name: mysecret
           key: password

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: cmVkaGF0


# echo -n "redhat" | base64

# output :- cmVkaGF0

# kubectl get secret mysecret -o yaml